;***SFR AND GPR EQUATE SECTION
PORTD EQU 8H
TRISD EQU 88H
STATUS EQU 03H
COUNT EQU 20H
COUNT1 EQU 21H

;***CONFIGURATION SETTINGS
    LIST  P=16F877A
    ORG  0
    GOTO START
    __CONFIG  H'3F79'
		
;***DELAY SUBROUTINE
DELAY   
    MOVLW      .255
    MOVWF      COUNT
    MOVLW      .255
    MOVWF      COUNT1	
A   
    DECFSZ     COUNT,1
    GOTO       A	
    DECFSZ     COUNT1,1
    GOTO       A
    RETLW      0
    
;***MAIN PROGRAM STARTED
    
START
;***PORT PINS INPUT/OUTPUT CONFIGURATION
    BANKSEL TRISD
    MOVLW   B'00000000'
    MOVWF   TRISD
    BANKSEL PORTD
    CLRF    PORTD
LOOP
    MOVLW     H'FF'
    MOVWF     PORTD
    CALL      DELAY
    MOVLW     H'00'
    MOVWF     PORTD
    CALL      DELAY
    GOTO      LOOP   ;FOR REPITITION OF SAME TASK
    END


