;***SFR AND GPR EQUATE SECTION
PORTB EQU 06H
TRISB EQU 86H
PORTD EQU 8H
TRISD EQU 88H
STATUS EQU 03H
COUNT EQU 20H
COUNT1 EQU 21H
;***CONFIGURATION SETTINGS
    LIST  P=16F877A
    ORG  0
    GOTO START
    __CONFIG  H'3F79'		    
;***MAIN PROGRAM STARTED   
START
;***PORT PINS INPUT/OUTPUT CONFIGURATION
    BANKSEL TRISB
    MOVLW   B'00000001'  ;FOR SETTING PORTB PIN 0 AS INPUT
    MOVWF   TRISB
    MOVLW   B'00000000'  ;FOR SETTING PORTD AS OUTPUT
    MOVWF   TRISD
    BANKSEL PORTD
    CLRF    PORTD
LOOP
    MOVLW     H'00'
    MOVWF     PORTD
LOOP1   
    BTFSS     PORTB,0
    GOTO      LOOP
    MOVLW     H'FF'
    MOVWF     PORTD
    GOTO      LOOP1  ;FOR REPITITION OF SAME TASK
    END





